#!/bin/sh

files=`git diff --cached --name-status`

if [[ $files =~ .circleci/config.pkl ]]; then
  pkl eval .circleci/config.pkl -o .circleci/config.yml
  git add .circleci/config.yml
fi

if [[ $files =~ \.github/ISSUE_TEMPLATE/.*\.pkl ]]; then
  for file in .github/ISSUE_TEMPLATE/*.pkl; do
    pkl eval $file -f yaml -o ${file%.pkl}.yml
    git add ${file%.pkl}.yml
  done
fi
