version: 2
updates:
- package-ecosystem: github-actions
  cooldown:
    default-days: 7
  directory: /
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  schedule:
    interval: weekly
