version = "3.10.0"
runner.dialect = scala3

maxColumn = 100

docstrings.style = Asterisk
docstrings.blankFirstLine = yes
docstrings.wrap = yes

rewrite.scala3.removeOptionalBraces = false
rewrite.insertBraces.minLines = 1 // Or 2
rewrite.insertBraces.allBlocks = true
