/*
 * Copyright © 2026 Apple Inc. and the Pkl project authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pkl.core.generator;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;
import org.snakeyaml.engine.v2.api.Load;
import org.snakeyaml.engine.v2.api.LoadSettings;

/**
 * Generates the {@code pkl:url} conformance snippet-test input from web-platform-tests {@code
 * urltestdata.json}.
 *
 * <p>The fixtures are downloaded on each run rather than checked into the repository: this
 * generator is only ever run by hand, so regenerating always picks up the latest upstream fixtures.
 *
 * <p>The generated module carries only <em>data</em>: it amends {@code
 * input-helper/api/wptUrl.pkl}, which holds the hand-written comparison logic.
 *
 * <p>Expectation fields that WHATWG expects to be empty are omitted, since {@code TestCase}
 * defaults them to {@code ""}. The exceptions are {@code origin} and {@code searchParams}, which
 * are compared only when stated and so are emitted even when empty.
 */
public final class WptUrlTestGenerator {
  /** The expectation fields we compare, in the order they are emitted. */
  private static final List<String> EXPECTATION_FIELDS =
      List.of(
          "href",
          "protocol",
          "username",
          "password",
          "hostname",
          "port",
          "pathname",
          "search",
          "hash");

  private static final List<String> OPTIONAL_EXPECTATION_FIELDS = List.of("origin", "searchParams");

  private WptUrlTestGenerator() {}

  public static void main(String[] args) {
    if (args.length < 2) {
      throw new IllegalArgumentException(
          "Usage: WptUrlTestGenerator <urltestdata.json-url> <output-file>");
    }
    var cases = readCases(URI.create(args[0]));
    write(Path.of(args[1]), render(cases));
  }

  @SuppressWarnings("unchecked")
  private static List<Map<String, Object>> readCases(URI testDataUri) {
    var json = download(testDataUri);
    // JSON is a subset of YAML 1.2, so the YAML loader already on the build classpath can read it.
    var loaded = (List<Object>) new Load(LoadSettings.builder().build()).loadFromString(json);
    // `urltestdata.json` interleaves section-heading strings between the case objects.
    return loaded.stream()
        .filter(entry -> entry instanceof Map)
        .map(entry -> (Map<String, Object>) entry)
        .toList();
  }

  private static String download(URI uri) {
    try (var in = uri.toURL().openStream()) {
      return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    } catch (IOException e) {
      throw new UncheckedIOException("Failed to download `" + uri + "`.", e);
    }
  }

  private static String render(List<Map<String, Object>> cases) {
    var out = new StringBuilder();
    out.append("/// DO NOT EDIT — generated by WptUrlTestGenerator from web-platform-tests'\n");
    out.append("/// `urltestdata.json`. See `input-helper/api/wptUrl.pkl` for how to regenerate\n");
    out.append("/// and for what is compared.\n");
    out.append("amends \".../input-helper/api/wptUrl.pkl\"\n");
    out.append("\n");
    out.append("cases {\n");
    for (var testCase : cases) {
      renderCase(out, testCase);
    }
    out.append("}\n");
    return out.toString();
  }

  private static void renderCase(StringBuilder out, Map<String, Object> testCase) {
    out.append("  new {\n");
    appendProperty(out, "input", requiredString(testCase, "input"));

    var base = optionalString(testCase, "base");
    if (base != null) {
      appendProperty(out, "base", base);
    }

    if (Boolean.TRUE.equals(testCase.get("failure"))) {
      out.append("    failure = true\n");
    } else {
      for (var field : EXPECTATION_FIELDS) {
        var value = optionalString(testCase, field);
        // `TestCase` defaults every expectation field to "", so empty ones need no line.
        if (value != null && !value.isEmpty()) {
          appendProperty(out, field, value);
        }
      }
      for (var field : OPTIONAL_EXPECTATION_FIELDS) {
        var value = optionalString(testCase, field);
        if (value != null) {
          appendProperty(out, field, value);
        }
      }
    }
    out.append("  }\n");
  }

  /** Reads a field that every case must carry, failing loudly if the fixtures are malformed. */
  private static String requiredString(Map<String, Object> testCase, String field) {
    var value = testCase.get(field);
    if (!(value instanceof String string)) {
      throw new IllegalArgumentException(
          "Expected case field `" + field + "` to be a string, but got: " + value);
    }
    return string;
  }

  /** Reads an optional field, treating both "absent" and JSON {@code null} as absent. */
  private static @Nullable String optionalString(Map<String, Object> testCase, String field) {
    return testCase.get(field) instanceof String string ? string : null;
  }

  private static void appendProperty(StringBuilder out, String name, String value) {
    out.append("    ").append(name).append(" = ");
    appendStringLiteral(out, value);
    out.append('\n');
  }

  /**
   * Appends {@code value} as a Pkl string literal.
   *
   * <p>Pkl's braced unicode escape ({@code \\u{...}}) covers every code point, so no surrogate
   * handling is needed. Control characters and the Unicode line separators are escaped because they
   * would otherwise terminate or corrupt the literal; other non-ASCII characters are emitted
   * literally, since the generated file is UTF-8.
   */
  private static void appendStringLiteral(StringBuilder out, String value) {
    out.append('"');
    value
        .codePoints()
        .forEach(
            cp -> {
              switch (cp) {
                case '\\' -> out.append("\\\\");
                case '"' -> out.append("\\\"");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                  if (isEscapeRequired(cp)) {
                    out.append("\\u{").append(Integer.toHexString(cp)).append('}');
                  } else {
                    out.appendCodePoint(cp);
                  }
                }
              }
            });
    out.append('"');
  }

  private static boolean isEscapeRequired(int cp) {
    return cp < 0x20 // C0 controls
        || (cp >= 0x7F && cp <= 0x9F) // DEL and C1 controls
        || cp == 0x2028 // LINE SEPARATOR
        || cp == 0x2029; // PARAGRAPH SEPARATOR
  }

  private static void write(Path outputFile, String content) {
    try {
      var parent = outputFile.getParent();
      if (parent != null) {
        Files.createDirectories(parent);
      }
      Files.writeString(outputFile, content, StandardCharsets.UTF_8);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }
}
