= Pkl 0.31 Release Notes
:version: 0.31
:version-minor: 0.XX.0
:release-date: TBD

include::ROOT:partial$component-attributes.adoc[]

Pkl {version} was released on {release-date}. +
[.small]#The latest bugfix release is {version-minor}. (xref:changelog.adoc[All Versions])#

The next release (0.XX) is scheduled for ???..
To see what's coming in the future, follow the {uri-pkl-roadmap}[Pkl Roadmap].

Please send feedback and questions to https://github.com/apple/pkl/discussions[GitHub Discussions], or submit an issue on https://github.com/apple/pkl/issues/new[GitHub]. +

[small]#Pkl is hosted on https://github.com/apple/pkl[GitHub].
To get started, follow xref:pkl-cli:index.adoc#installation[Installation].#

== Highlights [small]#💖#

News you don't want to miss.

=== XXX

== Noteworthy [small]#🎶#

Ready when you need them.

=== Standard Library changes

New properties have been added to the standard library (https://github.com/apple/pkl/pull/1396[#1396]).

==== Additions to `pkl:base`

The following APIs have been added:

* link:{uri-stdlib-List}#isNotEmpty[`List.isNotEmpty`]
* link:{uri-stdlib-Map}#isNotEmpty[`Map.isNotEmpty`]
* link:{uri-stdlib-Set}#isNotEmpty[`Set.isNotEmpty`]
* link:{uri-stdlib-Listing}#isNotEmpty[`Listing.isNotEmpty`]
* link:{uri-stdlib-Mapping}#isNotEmpty[`Mapping.isNotEmpty`]
* link:{uri-stdlib-String}#isNotEmpty[`String.isNotEmpty`]
* link:{uri-stdlib-String}#isNotBlank[`String.isNotBlank`]

== Breaking Changes [small]#💔#

Things to watch out for when upgrading.

=== Rule changes when loading external readers

The following changes have been made when loading external readers:

1. Executable paths declared inside a PklProject file are resolved relative to the enclosing directory, instead of the current working directory.
2. The `--external-module-reader` and `--external-resource-reader` CLI flags will _replace_ any external readers otherwise configured within a PklProject, instead of add to it. +
+
This makes this behavior consistent with how other settings work.

== Miscellaneous [small]#🐸#

* XXX

== Bugs fixed [small]#🐜#

The following bugs have been fixed.

* XXX (https://github.com/apple/pkl/issues/XXX[XXX])

== Contributors [small]#🙏#

We would like to thank the contributors to this release (in alphabetical order):

* XXX
