= Pkl 0.33 Release Notes
:version: 0.33
:version-minor: 0.33.0
:release-date: XXX
:version-next: 0.34
:version-next-date: February 2027

include::partial$intro.adoc[]

== Highlights [small]#💖#

=== XXX

== Noteworthy [small]#🎶#

=== XXX

== Breaking Changes [small]#💔#

=== Removal of macOS amd64 (Intel) Binaries

Native `pkl` and `pkldoc` binaries for Intel Mac systems are no longer published with Pkl releases.

To continue running new Pkl releases on these systems, use an appropriate Java runtime and the `jpkl` and `jpkldoc` Java executables.

=== Type check changes for `Class<T>`

In prior versions of Pkl, type arguments to the `Class` type were erased.
Any `Class` value would typecheck against `Class<T>` for any value of `T`.

In Pkl 0.33, this erasure has been removed.
A `Class` value typechecked against `Class<T>` must be a subclass of `T`.

If `T` does not resolve to a class type (i.e. it is a union type, nullable type, string literal type, parameterized type, or `nothing`), the type check will always fail.

=== XXX

== Bug Fixes [small]#🐜#

* XXX

== Contributors [small]#🙏#

We would like to thank the contributors to this release (in alphabetical order):

* XXX
