= Pkl 0.33 Release Notes
:version: 0.33
:version-minor: 0.33.0
:release-date: XXX
:version-next: 0.34
:version-next-date: February 2027

include::partial$intro.adoc[]

== Highlights [small]#💖#

=== XXX

== Noteworthy [small]#🎶#

=== CLI Changes

==== Default file locations

For new setups, the CLI no longer stores anything under `~/.pkl` (https://github.com/apple/pkl/pull/1674[#1674]).

It uses XDG-style locations on Unix and Known Folder locations on Windows:

[cols="1,2,2,2",options="header"]
|===
| Concern | Unix (Linux/macOS) | Windows | Legacy fallback

| Package cache
| `~/.cache/pkl`
| `$LOCALAPPDATA/pkl/Cache`
| none

| Settings file
| `~/.config/pkl/settings.pkl`
| `$APPDATA/pkl/settings.pkl`
| `~/.pkl/settings.pkl`

| CA certificates
| `~/.config/pkl/cacerts`
| `$APPDATA/pkl/cacerts`
| `~/.pkl/cacerts`

| REPL history
| `~/.local/state/pkl/repl-history`
| `$LOCALAPPDATA/pkl/repl-history`
| none
|===

On every OS, these locations can be overriden with XDG-style env vars.
For example, setting `XDG_CACHE_HOME` will configure the cache directory.

Note that the existing `~/.pkl/cache` directory is ignored, so Pkl will download packages to populate its cache if configured to do so.

== Breaking Changes [small]#💔#

=== Removal of macOS amd64 (Intel) Binaries

Native `pkl` and `pkldoc` binaries for Intel Mac systems are no longer published with Pkl releases.

To continue running new Pkl releases on these systems, use an appropriate Java runtime and the `jpkl` and `jpkldoc` Java executables.

=== XXX

== Bug Fixes [small]#🐜#

* XXX

== Contributors [small]#🙏#

We would like to thank the contributors to this release (in alphabetical order):

* XXX
