start_timestamp_ms: 0
end_timestamp_ms: 100
people: {
  key: "Pigeon"
  value: {
    name: "Pigeon"
    profile: {
      isExtinct: false
    }
    fictional: true
    height: 1.77
    hobbies: "cooing"
    role: Lead
  }
}
people: {
  key: "Parrot"
  value: {
    name: "Parrot"
    fictional: true
    height: 1.76
    hobbies: "singing"
    role: Lead
  }
}
owner: "Pigeon"
